version: '3.7'

services:
  grafana:
    image: grafana/grafana:${grafana_version}
    ports:
      - "3000:3000"
    networks:
      - default
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:${prometheus_version}
    volumes:
      - ./prometheus:/etc/prometheus
    expose:
      - 9090
    ports:
      - "9090:9090"
    networks:
      - default
    depends_on:
      - alertmanager
      - health-exporter

  alertmanager:
    image: prom/alertmanager:${alertmanager_version}
    volumes:
      - ./alertmanager:/etc/alertmanager
    expose:
      - 9093
    ports:
      - "9093:9093"
    networks:
      - default
        
  health-exporter:
    image: jianminhuang/health-exporter:latest
    expose:
      - 5000
    environment:
      - SERVER_INFO={"funpodium":{"url":"https://www.funpodium.net"},"rb88_platform_gateway2":{"url":"http://shprbp2.funpo.com:2041/actuator/health"},"rb88_gateway4":{"url":"http://shprbp4.funpo.com:2900/actuator/health"},"rb88_member_service4":{"url":"http://shprbp4.funpo.com:3700/actuator/health"},"rb88_transaction_service6":{"url":"http://shprbp6.funpo.com:3500/actuator/health"},"rb88_wallet_service6":{"url":"http://shprbp6.funpo.com:3600/actuator/health"},"Betway_Alipay_gateway1":{"url":"http://shpbwp1.funpo.com:2041/actuator/health"},"Betway_Alipay_velocity1":{"url":"http://shpbwp1.funpo.com:2400/actuator/health"},"Betway_Alipay_3rd_party1":{"url":"http://shpbwp1.funpo.com:3300/actuator/health"},"Fun88_Alipay_gateway1":{"url":"http://shpfnp1.funpo.com:2041/actuator/health"},"Fun88_Alipay_velocity1":{"url":"http://shpfnp1.funpo.com:2400/actuator/health"},"Fun88_Alipay_3rd_party1":{"url":"http://shpfnp1.funpo.com:3300/actuator/health"},"TLC_Alipay_gateway1":{"url":"http://shptlcp1.funpo.com:2041/actuator/health"},"TLC_Alipay_velocity1":{"url":"http://shptlcp1.funpo.com:2400/actuator/health"},"TLC_Alipay_3rd_party1":{"url":"http://shptlcp1.funpo.com:3300/actuator/health"},"JBO_Alipay_gateway1":{"url":"http://shpjbop1.funpo.com:2041/actuator/health"},"JBO_Alipay_velocity1":{"url":"http://shpjbop1.funpo.com:2400/actuator/health"},"JBO_Alipay_3rd_party1":{"url":"http://shpjbop1.funpo.com:3300/actuator/health"},"NSport_Api":{"url":"https://api.npse.com:8081"},"Cert":{"metric":"http://shfcertcny1.crtmgt8.com:4800/api/v2.0/appleAccounts?currentPage=1&perPageSize=50","method":"GET","expr":"body[\"page\"][\"totalCount\"]"}}
    networks:
      - default

networks:
  default:
