version: '3.7'

services:
  grafana:
    image: grafana/grafana:${grafana_version}
    ports:
      - "3000:3000"
    networks:
      - default
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:${prometheus_version}
    volumes:
      - ./prometheus:/etc/prometheus
    expose:
      - 9090
    ports:
      - "9090:9090"
    networks:
      - default
    depends_on:
      - alertmanager
      - health-exporter

  alertmanager:
    image: prom/alertmanager:${alertmanager_version}
    volumes:
      - ./alertmanager:/etc/alertmanager
    expose:
      - 9093
    ports:
      - "9093:9093"
    networks:
      - default
        
  health-exporter:
    image: jianminhuang/health-exporter:latest
    expose:
      - 5000
    environment:
      - SERVER_INFO={"funpodium":{"url":"https://www.funpodium.net"},"google":{"url":"https://www.google.com.tw"},"yahoo":{"url":"https://www.yahoo.com.tw"}}
    networks:
      - default

networks:
  default:
